routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Illuminate\Routing\RouteGroup;

// User route
Route::get('/', function () {
    return view('User.pages.landing.index');
})->name('landing');
Route::get('/login', 'Auth\AuthController@index')->middleware('guest')->name('auth.login');
Route::get('/logout', 'Auth\AuthController@logout')->name('auth.logout');
Route::post('/postLogin', 'Auth\AuthController@postLogin')->middleware('guest')->name('auth.postLogin');
Route::get('/registration', 'Auth\AuthController@registration')->middleware('guest')->name('auth.registration');
Route::get('/user/verify/{token}', 'Auth\AuthController@verify')->middleware('guest')->name('auth.verify');
Route::post('/registration', 'Auth\AuthController@postRegistration')->middleware('guest')->name('auth.postRegistration');
Route::get('/reset-password', 'Auth\AuthController@resetPassword')->middleware('guest')->name('auth.resetPassword');
Route::post('/reset-password/send', 'Auth\AuthController@sendResetMail')->middleware('guest')->name('auth.sendResetMail');
Route::get('/reset-password/new-password/{id}', 'Auth\AuthController@newPassword')->middleware('guest')->name('auth.newPassword');
Route::post('/reset-password/store', 'Auth\AuthController@storeNewPassword')->middleware('guest')->name('auth.store.newPassword');
Route::get('/resend', 'Auth\AuthController@resend')->middleware('guest')->name('auth.resend');
Route::get('/help', 'Auth\AuthController@help')->middleware('guest')->name('auth.help');
Route::post('/resend/store', 'Auth\AuthController@resendStore')->middleware('guest')->name('auth.resend.store');

Route::group(['middleware' => ['authCheck:user']], function () {
    Route::get('/dashboard', 'User\DashboardController@index')->name('user.dashboard');
    Route::get('/pretest/start', 'User\PretestController@index')->name('user.pretest');
    Route::get('/pretest', 'User\PretestController@landing')->name('user.before.pretest');
    Route::post('/pretest', 'User\PretestController@submit')->name('user.pretest.submit');
    Route::get('/pretest/result', 'User\PretestController@set_section_recomend');

    // Courses
    Route::get('/courses', 'User\CourseController@index')->name('user.course.index');
    Route::get('/courses/{id}/show', 'User\CourseController@show')->name('user.course.show');
    Route::get('/courses/{section}/video', 'User\CourseController@video')->name('user.course.video');

    
    // All Courses
    Route::get('/courses/all', 'User\AllCourseController@index')->name('user.course.all');
    Route::get('/courses/all/{id}/show', 'User\AllCourseController@show')->name('user.course.all.show');
    Route::get('/courses/all/{section}/video', 'User\AllCourseController@video')->name('user.course.all.video');


    //sessiom TEST
    Route::get('/session/{section}/test', 'User\SessionController@index')->name('user.session.start');
    Route::post('/session', 'User\SessionController@submit')->name('user.session.submit');
    Route::get('/session/report', 'User\SessionController@report')->name('user.session.report');

    // profile
    Route::get('/profile/change-password', 'User\ProfileController@changePassword')->name('profile.change');
    Route::Post('/profile/change-password/store', 'User\ProfileController@updatePassword')->name('profile.update.password');
    Route::get('/profile/basic', 'User\ProfileController@basic')->name('profile.basic');
    Route::resource('/profile', 'User\ProfileController')->except(['destroy, create, edit, update']);
});



// Admin Route
Route::group(['prefix' => 'admin'], function () {
    // Auth
    Route::get('/login', 'Admin\AdminController@login')->name('AdminLogin')->middleware('guest');
    Route::post('/loginProses', 'Admin\AdminController@loginProses')->name('AdminLoginProses')->middleware('guest');
    Route::get('/logout', 'Admin\AdminController@logout')->name('AdminLogout');

    Route::group(['middleware' => ['authCheck:admin']], function () {
        // Dashboard
        Route::get('/', 'Admin\AdminDashboard@index')->name('AdminDashboard');
        // User
        Route::get('/user', 'Admin\AdminUser@index')->name('AdminUser');
        Route::get('/getDataUser', 'Admin\AdminUser@getData')->name('getUserData');
        Route::get('/export-score', 'Admin\AdminUser@exportScore')->name('getSessionResutl');
        Route::post('/user/reset', 'Admin\AdminUser@userReset')->name('AdminUserReset');
        Route::get('/user/{id}/show', 'Admin\AdminUser@show')->name('AdminShowUser');

        // Courses
        Route::get('/courses', 'Admin\CourseController@index')->name('AdminCourses');
        Route::get('/courses/add', 'Admin\CourseController@create')->name('AdminCourseAdd');
        Route::get('/courses/edit/{id}', 'Admin\CourseController@edit')->name('AdminCourseEdit')->where('name', '[A-Za-z0-9]+');
        Route::patch('/courses/update', 'Admin\CourseController@update')->name('AdminCourseUpdate');
        Route::get('/courses/delete', 'Admin\CourseController@destroy')->name('AdminCourseDel');
        Route::get('/courses/multiDelete', 'Admin\CourseController@multiDelete')->name('AdminCourseMultiDel');
        Route::get('/courses/getDataCourses', 'Admin\CourseController@getDataCourses')->name('getDataCourses');
        Route::post('/courses/add', 'Admin\CourseController@store')->name('AdminCourseStore');
        Route::post('/courses/import', 'Admin\CourseController@import')->name('AdminCourseImport');
        Route::get('/courses/{id}', 'Admin\SectionController@show')->name('AdminShowSection');
        Route::get('/courses/active/{id}', 'Admin\CourseController@active')->name('AdminCourseActive');

        // Sections
        Route::get('/sections', 'Admin\SectionController@index')->name('AdminSections');
        Route::get('/sections/getData', 'Admin\SectionController@getData')->name('getDataSections');
        Route::get('/sections/add', 'Admin\SectionController@create')->name('AdminSectionAdd');
        Route::post('/sections/add', 'Admin\SectionController@store')->name('AdminSectionStore');
        Route::get('/sections/edit/{id}', 'Admin\SectionController@edit')->name('AdminSectionEdit')->where('name', '[A-Za-z0-9]+');
        Route::patch('/sections/update', 'Admin\SectionController@update')->name('AdminSectionUpdate');
        Route::get('/sections/delete', 'Admin\SectionController@destroy')->name('AdminSectionDel');
        Route::get('/sections/multiDelete', 'Admin\SectionController@multiDelete')->name('AdminSectionMultiDel');
        Route::post('/sections/import', 'Admin\SectionController@import')->name('AdminSectionImport');

        // Lecture
        Route::get('/lecture', 'Admin\LectureController@index')->name('AdminLecture');
        // Route::get('/lecture/getData', 'Admin\LectureController@getData')->name('getDataLecture');
        Route::get('/lecture/add', 'Admin\LectureController@create')->name('AdminLectureAdd');
        Route::post('/lecture/add', 'Admin\LectureController@store')->name('AdminLectureStore');
        Route::get('/lecture/edit/{id}', 'Admin\LectureController@edit')->name('AdminLectureEdit')->where('name', '[A-Za-z0-9]+');
        Route::patch('/lecture/update', 'Admin\LectureController@update')->name('AdminLectureUpdate');
        Route::get('/lecture/delete', 'Admin\LectureController@destroy')->name('AdminLectureDel');
        Route::get('/lecture/multiDelete', 'Admin\LectureController@multiDelete')->name('AdminLectureMultiDel');
        Route::post('/lecture/import', 'Admin\LectureController@import')->name('AdminLectureImport');

        // pretest (jika tambah route maka sebelum resaour)
        Route::get('/pre-tests/destroy', 'Admin\PretestController@destroy')->name('pre-tests.destroy');
        Route::get('/pre-tests/multiDelete', 'Admin\PretestController@multiDelete')->name('pre-tests.multiDelete');
        Route::post('/pre-tests/import', 'Admin\PretestController@import')->name('pre-tests.import');
        Route::resource('pre-tests', 'Admin\PretestController')->except([
            'destroy'
        ]);

        // Session Test
        Route::get('/session-tests/lecture', 'Admin\SessionController@getLecture')->name('session-tests.get.lecture');
        Route::get('/session-tests/destroy', 'Admin\SessionController@destroy')->name('session-tests.destroy');
        Route::get('/session-tests/multiDelete', 'Admin\SessionController@multiDelete')->name('session-tests.multiDelete');
        Route::post('/session-tests/import', 'Admin\SessionController@import')->name('session-tests.import');
        Route::get('/sessesion-tests/set-pretest', 'Admin\SessionController@setPretest')->name('session-tests.setPretest');
        Route::resource('session-tests', 'Admin\SessionController')->except([
            'destroy'
        ]);
    });
});

app/Http/Controllers/Admin/SessionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\Generate;
use App\Http\Controllers\Controller;
use App\Imports\SessionImport;
use App\Models\Lecture;
use App\Models\Section;
use App\Models\Session_question;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Maatwebsite\Excel\Facades\Excel;

class SessionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $req, Session_question $session)
    {
        $limit = 100;
        $key = (!empty($req->key)) ? $req->key : '';
        $data = $session->latest()->with('section')
                        ->orWhere('question', 'like', '%'.$key.'%')
                        ->orderBy('section_id', 'DESC')
                        ->simplePaginate($limit);
        // dd($data);
        if ($req->ajax()) {
            return view('Admin.pages.session.tbody')->with('data', $data)->render();
        }
        return view('Admin.pages.session.index')->with('data', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = Section::orderBy('ordering')->get();
        return view('Admin.pages.session.create')
                    ->with('data', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $req)
    {
        $req->validate([
            'section_id' => 'required',
            'lecture_id' => 'required',
            'question' => 'required',
            'answer_a' => 'required',
            'answer_b' => 'required',
            'answer_c' => 'required',
            'answer_d' => 'required',
            'right' => 'required',
        ]);
        $data = Session_question::insert([
            'id' => Generate::id(),
            'section_id' => $req->section_id,
            'lecture_id' => $req->lecture_id,
            'set_pretest' => $req->set_pretest,
            'question' => $req->question,
            'answer_a' => $req->answer_a,
            'answer_b' => $req->answer_b,
            'answer_c' => $req->answer_c,
            'answer_d' => $req->answer_d,
            'right' => $req->right
        ]);

        return redirect()->route('session-tests.index');
    }

    /**
     * Display the Sections Select by Course ID
     *
     * @param  \App\Models\Session_question  $session_question
     * @return \Illuminate\Http\Response
     */
    public function show(Request $req, Session_question $session)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Session_question  $session_question
     * @return \Illuminate\Http\Response
     */
    public function edit($id, Session_question $session)
    {
        $data = Section::orderBy('ordering')->get();
        // dd($data);
        $item = $session->findOrFail($id);
        return view('Admin.pages.session.update')->with('data', $data)
                                                ->with('item', $item);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Session_question  $session_question
     * @return \Illuminate\Http\Response
     */
    public function update(Request $req, $id, Session_question $session_question)
    {
        $req->validate([
            'section_id' => 'required',
            'lecture_id' => 'required',
            'question' => 'required',
            'answer_a' => 'required',
            'answer_b' => 'required',
            'answer_c' => 'required',
            'answer_d' => 'required',
            'right' => 'required',
        ]);

        $data = $session_question->where('id', $id)->update([
            'section_id' => $req->section_id,
            'lecture_id' => $req->lecture_id,
            'set_pretest' => $req->set_pretest,
            'question' => $req->question,
            'answer_a' => $req->answer_a,
            'answer_b' => $req->answer_b,
            'answer_c' => $req->answer_c,
            'answer_d' => $req->answer_d,
            'right' => $req->right
        ]);

        return redirect()->route('session-tests.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Session_question  $session_question
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $req, Session_question $session_question)
    {
        if ($req->ajax()) {
            // // hapus data
            $session_question->where('id', $req->id)->delete();
        }
        $res = [
            'status' => 'success'
        ];

        echo json_encode($res);
    }

    public function multiDelete(Request $req)
    {
        if ($req->ajax()) {
            $id = $req->id;
            $data = Session_question::whereIn('id', $id);
            $status = $data->delete();
            if ($status) {
                $res = ['status' => 'success'];
            } else {
                $res = ['status' => 'cancel'];
            }
        }
        echo json_encode($res);
    }

    public function import(Request $req)
    {
        $req->validate([
            'file' => 'required|mimes:csv,xlsx,xls'
        ]);

        $file = $req->file;
        $fileName = date('YmdHis').".". $file->getClientOriginalExtension();
        $pathUpload = "images/session/import/";
        $file->move($pathUpload, $fileName);
        $filePath = public_path($pathUpload.$fileName);
        Excel::import(new SessionImport, $filePath);
        File::delete($filePath);
        
        return redirect()->route('session-tests.index');
    }

    public function getLecture(Request $req)
    {
        $option = '';
        $id = $req->id;
        $lectures = Lecture::where('section_id', $id)->orderBy('ordering')->get();
        foreach ($lectures as $item) {
            $option .="<option value='". $item->id."'>".$item->title."</option>";
        }
        echo $option;
    }

    public function setPretest(Request $req)
    {
        if($req->ajax())
        {
            $question = Session_question::where('id', $req->id)->first();
            $question->set_pretest = !$question->set_pretest;
            $question->save();

            echo $question->set_pretest;
        }
    }
}

resources/views/Admin/pages/session/create.blade.php
@extends('Admin.layout.default')
@section('sidebar-sessions', 'bg-white')

@section('title','Admin Create Question')

@section('content')
<main class="bg-white-300 flex-1 mx-5 my-5 overflow-x-hidden">
    <div class="text-gray-900 bg-gray-100">
        <div class="mx-4 py-2 flex w-full">
            <h1 class="text-2xl mr-auto border-b border-gray-400 text-gray-700 pb-2 w-full">
                Add New Question
            </h1>
        </div>
        <div class="px-5 flex w-full">
            <form action="{{ route('session-tests.store') }}" method="post" class="w-full" enctype="multipart/form-data"
                id="created">
                @csrf
                <div class="flex flex-row">
                    <div class="flex flex-col w-full mt-5 mr-2">
                        <label class="block tracking-wide text-gray-700 pb-3" for="grid-state">
                            Section
                        </label>
                        <div class="relative">
                            <select id="select_section" name="section_id" class="block border border-gray-400 appearance-none w-full bg-white border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-state">
                                <option value="">---- Select Section ----</option>
                                @foreach ($data as $item)
                                <option value="{{ $item->id }}" @if($item->course_id == old('section_id')) selected @endif>
                                    {{ $item->title }}
                                </option>
                                @endforeach
                            </select>
                            <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
                            </div>
                        </div>
                        @error('section_id')
                        <div class="">
                            <p id="erorTitle" class="text-sm text-red-600 mx-2 py-2">{{ $message }}</p>
                        </div>
                        @enderror
                    </div>
                    <div class="flex flex-col w-full mt-5">
                        <label class="block tracking-wide text-gray-700 pb-3" for="grid-state">
                            Lecture
                        </label>
                        <div class="relative">
                            <select id="select_lecture" name="lecture_id" class="block border border-gray-400 appearance-none w-full bg-white border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-state">
                                <option value="">---- Select Lecture ----</option>
                            </select>
                            <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
                            </div>
                        </div>
                        @error('lecture_id')
                        <div class="">
                            <p id="erorTitle" class="text-sm text-red-600 mx-2 py-2">{{ $message }}</p>
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="flex flex-col w-3/12">
                    <div class="flex mt-6">
                        <label class="flex items-center">
                            <input type="checkbox" class="form-checkbox" name="set_pretest" value="1">
                            <span class="ml-2 text-gray-700">Set As Pretest Question</span></span>
                        </label>
                        </div>
                    @error('set_pretest')
                    <div class="">
                        <p id="erorTitle" class="text-sm text-red-600 mx-2 py-2">{{ $message }}</p>
                    </div>
                    @enderror
                </div>
                <div class="flex flex-col w-full mt-5">
                    <label for="question" class="text-gray-700 font-roboto pb-3">Question</label>
                    <textarea name="question" id="question"  
                        class="w-full border border-gray-400 rounded font-lato ">{{ old('question') }}</textarea>
                    @error('question')
                    <div class="">
                        <p id="erorTitle" class="text-sm text-red-600 mx-2 py-2">{{ $message }}</p>
                    </div>
                    @enderror
                </div>
                <div class="flex flex-row">
                    <div class="flex flex-col w-full mt-5 mr-1">
                        <label for="option" class="text-gray-700 font-roboto pb-3">Option 1</label>
                        <textarea name="answer_a" id="option"  
                            class="w-full border border-gray-400 rounded font-lato ">{{ old('answer_a') }}</textarea>
                        @error('answer_a')
                        <div class="">
                            <p id="erorTitle" class="text-sm text-red-600 mx-2 py-2">{{ $message }}</p>
                        </div>
                        @enderror
                    </div>
                    <div class="flex flex-col w-full mt-5 ml-1">
                        <label for="option" class="text-gray-700 font-roboto pb-3">Option 2</label>
                        <textarea name="answer_b" id="option"  
                            class="w-full border border-gray-400 rounded font-lato ">{{ old('answer_b') }}</textarea>
                        @error('answer_b')
                        <div class="">
                            <p id="erorTitle" class="text-sm text-red-600 mx-2 py-2">{{ $message }}</p>
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="flex flex-row">
                    <div class="flex flex-col w-full mt-5 mr-1">
                        <label for="option" class="text-gray-700 font-roboto pb-3">Option 3</label>
                        <textarea name="answer_c" id="option"  
                            class="w-full border border-gray-400 rounded font-lato ">{{ old('answer_c') }}</textarea>
                        @error('answer_c')
                        <div class="">
                            <p id="erorTitle" class="text-sm text-red-600 mx-2 py-2">{{ $message }}</p>
                        </div>
                        @enderror
                    </div>
                    <div class="flex flex-col w-full mt-5 ml-1">
                        <label for="option" class="text-gray-700 font-roboto pb-3">Option 4</label>
                        <textarea name="answer_d" id="option"  
                            class="w-full border border-gray-400 rounded font-lato ">{{ old('answer_d') }}</textarea>
                        @error('answer_d')
                        <div class="">
                            <p id="erorTitle" class="text-sm text-red-600 mx-2 py-2">{{ $message }}</p>
                        </div>
                        @enderror
                    </div>
                </div>
                <div class="flex flex-col w-full mt-5">
                    <label class="block tracking-wide text-gray-700 pb-3" for="grid-state">
                        Select Option Right
                      </label>
                      <div class="relative">
                        <select name="right" class="block border border-gray-400 appearance-none w-full bg-white border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500" id="grid-state">
                          <option value="">---- Select Option Right ----</option>
                          <option value="A">A</option>
                          <option value="B">B</option>
                          <option value="C">C</option>
                          <option value="D">D</option>
                          
                        </select>
                        <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                          <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z"/></svg>
                        </div>
                      </div>
                    @error('right')
                    <div class="">
                        <p id="erorTitle" class="text-sm text-red-600 mx-2 py-2">{{ $message }}</p>
                    </div>
                    @enderror
                </div>
                <div class="flex flex-row w-full mt-6">
                    <button type="submit" class="bg-green-800 text-white px-5 py-2 rounded">Submit</button>
                    <button type="reset" class="bg-red-800 text-white px-5 py-2 rounded mx-2">Reset</button>
                </div>
            </form>
        </div>
    </div>
</main>
@endsection

@section('js')
@include('Admin.pages.session.js')

<script>
    CKEDITOR.replace( 'question', {
        height: '8rem',
        customConfig: "{{ asset('ckeditor/config.js') }}"
    });

    option = ['a','b','c','d'];
    for(var i=0; i<= option.length; i++){
        var answer = 'answer_'+option[i];
        CKEDITOR.replace(answer, {
            height: '8rem',
        });
    }
</script>

@endsection

resources/views/Admin/pages/session/index.blade.php
@extends('Admin.layout.default')
@section('sidebar-sessions', 'bg-white')

@section('title','Admin Session Menu')

@section('content')
<main class="bg-white-100 w-5/6 px-3 pt-3 max-h-auto">
  <div class="text-gray-900 bg-gray-100 relative">
    <div class="p-4 flex w-full bg-white items-center">
      <h1 class="text-3xl mr-auto text-gray-700">
        Pretest Questions
      </h1>
      @error('file')
      <div class="h-auto flex items-center mx-2 bg-red-200 rounded px-3">
        <span class="text-red-900 text-sm align-middle">{{ $message }}</span>
      </div>
      @enderror
      <button class="" onclick="multiple_del()">
        <span class="bg-red-600 hover:bg-red-700 text-white text-sm py-3 px-4 rounded mr-2">Delete Selected</span>
      </button>
      <button data-modal='centeredFormModal' class="modal-trigger ">
        <span class="bg-blue-600 hover:bg-blue-700 text-white text-sm py-3 px-4 rounded">
          Import Data
        </span>
      </button>
      <a href="{{route('session-tests.create')}}" class="">
        <span class="text-sm px-3 py-3 bg-green-600 text-white rounded ml-2 hover:bg-green-700">
          Add New
        </span>
      </a>

      <div class="mr-0">
        <label for="search" class="px-5 text-gray-700">Serach</label>
        <input type="text" name="search" id="search" class="px-2 py-2 border-gray-400 border rounded">
      </div>
    </div>
    <hr>
    <div class="table">
      @include('Admin.pages.session.tbody')
    </div>
  </div>
</main>
@include('Admin.pages.session.modal')
@endsection

@section('js')
@include('Admin.pages.session.js')
@endsection

resources/views/Admin/pages/session/modal.blade.php
<div id='centeredFormModal' class="modal-wrapper">
  <div class="overlay close-modal"></div>
  <div class="modal modal-centered">
    <div class="modal-content shadow-lg p-5">
      <div class="border-b p-2 pb-3 pt-0 mb-2">
        <div class="flex justify-between items-center">
          Import From Excel
          <span class='close-modal cursor-pointer px-3 py-1 rounded-full bg-gray-100 hover:bg-gray-200'>
            <i class="fas fa-times text-gray-700"></i>
          </span>
        </div>
      </div>
      <!-- Modal content -->
      <form class="w-full h-auto flex flex-col justify-center" method="POST" action="{{ route('session-tests.import') }}"
        enctype="multipart/form-data">
        <div class="flex flex-col w-full justify-center items-center bg-gray-200 h-64">
          <label class="text-sm text-gray-800">Contoh Format, File Sebaiknya .xls</label>
          <img src="{{ asset('images/session/session-xls.png') }}" alt="Contoh Format File">
          <p class="text-gray-700" id="filename"></p>
          <label
            class="w-64 flex flex-col items-center px-4 py-2 bg-white text-blue rounded-lg tracking-wide uppercase border border-blue cursor-pointer hover:bg-gray-200 hover:border hover:border-gray-500">
            <span class="mt-2 text-base leading-normal text-gray-800">Select a File</span>
            <input type="file" name="file" id="file" class="hidden" />
          </label>
        </div>
        @csrf
        <div class="flex flex-row w-full justify-center mt-5">
          <button type="submit" class="bg-green-800 text-white px-10 py-2 rounded">Submit</button>
        </div>
      </form>
    </div>
  </div>
</div>

resources/views/Admin/pages/session/tbody.blade.php
<div id="scroll" class="px-3 py-3 flex justify-center overflow-y-auto h-rem28">
  <table class="w-full h-auto text-sm bg-white shadow-md rounded mb-4 text-gray-800">
    <thead class="">
      <tr class="border-b">
        <th class="text-center py-3 px-3 w-auto">
          <span class="text-xs">All</span><br>
          <input type="checkbox" onClick="select_all(this)" />
        </th>
        <th class="text-left p-3 px-5 w-auto">No.</th>
        <th class="text-left p-3 px-5 w-auto">Questions</th>
        <th class="text-left p-3 px-5 w-auto">Set Pretest</th>
        <th class="text-center p-3 px-5 w-2/12">Actions</th>
      </tr>
    </thead>
    <tbody class="">
      @forelse($data as $key => $item)
    @php
        $no = $key +1;
    @endphp
    <tr class="border-b hover:bg-gray-100 text-gray-700" id="content">
      <td class="py-3 px-3 text-center">
        <input type="checkbox" name="select_delete" id="multiple" value="{{ $item->id }}"> 
      </td>
      <td class="p-3 px-5">{{ $key+1 ?? null }}</td>
      <td class="p-3 px-5">{!! $item->question !!}</td>
      <td class="p-3 px-5">
          <div class="relative w-10">                
            <div id="line_toggle" class="w-full h-4 rounded-lg bg-gray-500 shadow-inner my-1"></div>
            <label onclick="setPretest('{{ $item->id }}')">
              <div id="{{ $item->id }}" class="w-6 h-6 rounded-full shadow-inner absolute top-0 -my-1 @if($item->set_pretest) bg-teal-600 right-0 @else bg-gray-200 left-0 @endif"></div>
            </label>
          </div>
      </td>
      <td class="p-3 text-center px-5 flex justify-end">
        <a id="btn-edit" href="{{ route("session-tests.edit", ["session_test"=> $item->id ]) }}"
          class="mr-3 bg-orange-500 hover:bg-orange-700 text-white py-1 px-2 rounded">
          <span class="iconify text-lg" data-icon="feather:edit" data-inline="false"></span>
        </a>
        <button onclick="btn_del('{{ $item->id }}')"
          class="bg-red-500 hover:bg-red-700 text-white py-1 px-2 rounded">
          <span class="iconify text-lg" data-icon="ic:round-delete" data-inline="false"></span>
        </button>
      </td>
    </tr>
@empty
  <tr class="border-b hover:bg-gray-100 text-gray-700">
    <td colspan="5" class="p-5 px-5 text-center">Session Questions Not Found</td>
  </tr>
@endforelse
    </tbody>
  </table>
</div>
<div class="w-full h-12 bg-white flex items-center">
  {{ $data->links('vendor.pagination.pagination') }}
</div>